services:
  api:
    build:
      context: .
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
    container_name: lamapi_api
    env_file:
      - ./.env
    command: gunicorn -w ${WORKERS} -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:5000 server:app
    ports:
      - "${LAMAPI_PORT}:5000"
    restart: always
    volumes:
      - ./api/:/app
      - ./scripts/:/scripts
    depends_on:
      - mongo
      - elastic
      - kibana

  mongo:
    image: mongo:${MONGO_VERSION}
    container_name: lamapi_mongo
    env_file:
      - ./.env
    ports:
      - "${MONGO_PORT}:27017"
    restart: always
    command: mongod --config /etc/mongod.conf
    volumes:
      - ./mongo-data:/data/db
      - ~/my-data:/data/my-data
      - ./mongod.conf:/etc/mongod.conf  # Custom MongoDB config


  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: lamapi_elastic
    volumes:
      - ./elasticdata:/usr/share/elasticsearch/data
    ports:
      - ${ELASTIC_PORT}:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.authc.api_key.enabled=false
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200 | grep -q 'You Know, for Search'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    depends_on:
      elastic:
        condition: service_healthy
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: lamapi_kibana
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    mem_limit: ${MEM_LIMIT}
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120