services:
  api:
    build:
      context: .
      args: 
        PYTHON_VERSION: ${PYTHON_VERSION}
    container_name: lamapi_api
    env_file:
      - ./.env
    command: bash -c "gunicorn -w $THREADS -k gevent -b 0.0.0.0:5000 server:app --timeout 300 --reload --log-level debug"
    ports:
      - "${LAMAPI_PORT}:5000"
    restart: always
    volumes:
      - ./api/:/app
      - ./scripts/:/scripts
  
  mongo:
    image: mongo:${MONGO_VERSION}
    container_name: lamapi_mongo
    env_file:
      - ./.env
    ports:
      - "${MONGO_PORT}:27017"
    restart: always   
    volumes:
      - C:/Users/a.belotti23/Documents/GitHub/mongo-data:/data/db
      - ~/my-data:/data/my-data
      
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: lamapi_elastic
    volumes:
      - ./certs:/usr/share/elasticsearch/config/certs
      - C:/Users/a.belotti23/Documents/GitHub/data/esdata01:/usr/share/elasticsearch/data
      - ./jvm.options:/usr/share/elasticsearch/config/jvm.options.d/jvm.options
    ports:
      - ${ELASTIC_PORT}:9200
    environment:
      - node.name=es01
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.transport.ssl.verification_mode=none
      - xpack.security.http.ssl.client_authentication=none
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 8G
    ulimits:
      memlock:
        soft: -1
        hard: -1

  es02:
    depends_on:
      - es01
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: lamapi_es02
    volumes:
      - ./certs:/usr/share/elasticsearch/config/certs
      - C:/Users/a.belotti23/Documents/GitHub/data/esdata02:/usr/share/elasticsearch/data
      - ./jvm.options:/usr/share/elasticsearch/config/jvm.options.d/jvm.options
    environment:
      - node.name=es02
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es01,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.transport.ssl.verification_mode=none
      - xpack.security.http.ssl.client_authentication=none
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 8G
    ulimits:
      memlock:
        soft: -1
        hard: -1

  es03:
    depends_on:
      - es02
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: lamapi_es03
    volumes:
      - ./certs:/usr/share/elasticsearch/config/certs
      - C:/Users/a.belotti23/Documents/GitHub/data/esdata03:/usr/share/elasticsearch/data
      - ./jvm.options:/usr/share/elasticsearch/config/jvm.options.d/jvm.options
    environment:
      - node.name=es03
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es01,es02
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.transport.ssl.verification_mode=none
      - xpack.security.http.ssl.client_authentication=none
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 8G
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    depends_on:
      - es01
      - es02
      - es03
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: lamapi_kibana
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es01:9200
    mem_limit: ${MEM_LIMIT}
    restart: always
